#!/bin/bash
# 新增算子开发快速参考

echo "=========================================="
echo "新增算子开发流程 - 快速参考"
echo "=========================================="
echo ""

echo "📋 Step 1: 检查实现可用性"
echo "----------------------------------------"
echo "□ 检查 PyTorch 官方:"
echo "    python -c \"import torch.nn.functional as F; print(hasattr(F, 'operator_name'))\""
echo ""
echo "□ 检查 vLLM:"
echo "    python -c \"import torch.ops._C as ops; print(hasattr(ops, 'operator_name'))\""
echo ""
echo "□ 决策:"
echo "    ✅ 有实现 → 继续 Step 2"
echo "    🚫 无实现 → 跳过，标记为待实现"
echo ""

echo "📝 Step 2: 实现算子代码"
echo "----------------------------------------"
echo "□ 创建文件:"
echo "    baseline/operators/category/operator_name.py"
echo ""
echo "□ 实现三层优先级:"
echo "    Layer 1: PyTorch 官方 (优先实现)"
echo "    Layer 2: vLLM CUDA (次选实现)"
echo "    Layer 3: 手动实现 (fallback)"
echo ""
echo "⚠️  重要: 如果有多种实现可用，需要性能测试对比"
echo "    最终以性能最优的实现作为基线！"
echo ""
echo "□ 必须实现的方法:"
echo "    - forward()         # 前向计算"
echo "    - compute_flops()   # FLOPs"
echo "    - compute_bytes()   # 访存量"
echo "    - prepare_inputs()  # 准备输入"
echo "    - compute_golden()  # Golden reference"
echo ""

echo "📊 Step 3: 创建测试用例"
echo "----------------------------------------"
echo "□ 查询 flashinfer-trace:"
echo "    ls /path/to/flashinfer-trace/*operator_name*"
echo ""
echo "□ 情况 A: 有真实 shape"
echo "    → 创建 6-10 个 workloads"
echo "    → 覆盖 decode/prefill 场景"
echo "    → 标注来源: \"flashinfer-trace: Model-Name\""
echo ""
echo "□ 情况 B: 无真实 shape"
echo "    → 使用大中小三个 shape"
echo "    → 标注来源: \"临时测试用例 - 大/中/小\""
echo "    → 添加 TODO: 后续从大模型抓取"
echo ""
echo "□ 创建 YAML:"
echo "    baseline/cases/category/operator_name.yaml"
echo ""

echo "✅ Step 4: 验证测试"
echo "----------------------------------------"
echo "□ 运行测试:"
echo "    python baseline/run.py run --backend nvidia \\"
echo "      --case baseline/cases/category/operator_name.yaml \\"
echo "      --platform nvidia_h20"
echo ""
echo "□ 检查项:"
echo "    ✓ 测试通过率 100%"
echo "    ✓ 相对误差 < 1e-2 (bf16)"
echo "    ✓ 长序列效率 > 60% (Attention)"
echo "    ✓ 大 batch 效率 > 70% (GEMM)"
echo ""
echo "□ 多实现性能对比 (如果有多种实现):"
echo "    ⚠️  关键: 测试所有可用实现的性能"
echo "    ⚠️  以性能最优的实现作为最终基线"
echo "    ✓ 测试 PyTorch 官方实现性能"
echo "    ✓ 测试 vLLM CUDA 实现性能 (如果有)"
echo "    ✓ 测试手动实现性能 (如果有)"
echo "    ✓ 记录性能对比数据到代码注释"
echo "    ✓ 选择最优实现并更新 forward() 方法"
echo ""

echo "=========================================="
echo "快速命令"
echo "=========================================="
echo ""
echo "# 1. 检查 PyTorch API"
echo "python -c \"import torch.nn.functional as F; print([x for x in dir(F) if 'your_keyword' in x.lower()])\""
echo ""
echo "# 2. 从模板创建算子"
echo "cp baseline/operators/basic/template.py baseline/operators/category/new_op.py"
echo ""
echo "# 3. 测试单个算子"
echo "python baseline/run.py run --backend nvidia --case baseline/cases/category/new_op.yaml --platform nvidia_h20"
echo ""
echo "# 4. 查看所有算子"
echo "python baseline/run.py list"
echo ""

echo "=========================================="
echo "常见问题"
echo "=========================================="
echo ""
echo "Q: PyTorch 和 vLLM 都没有实现怎么办？"
echo "A: 跳过该算子，标记为待实现，不要强行手动实现"
echo ""
echo "Q: flashinfer-trace 没有数据怎么办？"
echo "A: 使用大中小三个 shape 临时替代，标记 TODO"
echo ""
echo "Q: 测试失败怎么办？"
echo "A: 检查 forward() 实现、检查 Golden reference、手动对比输出"
echo ""
echo "Q: 性能不达标怎么办？"
echo "A: 确认使用 PyTorch 官方 API、检查 GPU 利用率、查看 Roofline 分析"
echo ""
echo "Q: 有多种实现时如何选择？"
echo "A: 进行性能对比测试，以性能最优的实现作为最终基线"
echo ""

echo "=========================================="
echo "详细文档: 新增算子开发流程.md"
echo "=========================================="
