"""用例生成器 — 组合 model + profile + operator mapping → YAML case 文件"""

import yaml
from pathlib import Path
from typing import Any

from .model_parser import ModelParams
from .param_mapping import load_operator_registry
from .profile_loader import Profile


def _make_workload_name(model: ModelParams, stage: str, var_axes: dict) -> str:
    """生成可读的 workload 名称"""
    parts = [model.name]
    if stage:
        parts.append(stage)
    # 添加关键的变化参数值
    for k, v in var_axes.items():
        parts.append(f"{k}{v}")
    return "_".join(parts)


def _make_source_desc(model: ModelParams, stage: str, var_axes: dict) -> str:
    """生成 source 描述"""
    var_desc = ", ".join(f"{k}={v}" for k, v in var_axes.items())
    return f"{model.name}, {stage}, {var_desc}"


def _infer_stage(var_axes: dict) -> str:
    """从 var_axes 推断 stage"""
    # 如果有 seqlen_q=1 或很小的 num_tokens，推断为 decode
    if var_axes.get("seqlen_q") == 1:
        return "decode"
    num_tokens = var_axes.get("num_tokens", 0)
    if isinstance(num_tokens, int) and num_tokens <= 64:
        return "decode"
    elif isinstance(num_tokens, int) and num_tokens >= 512:
        return "prefill"
    batch = var_axes.get("batch", var_axes.get("b", 0))
    if isinstance(batch, int) and batch > 0:
        seq = var_axes.get("seq_len", var_axes.get("max_seq", 0))
        return "decode" if var_axes.get("seqlen_q", 1) == 1 else "prefill"
    return "mixed"


def generate_case_yaml(
    model: ModelParams,
    operator_name: str,
    profile: Profile,
) -> dict | None:
    """为一个 (model, operator, profile) 组合生成 case dict。

    Returns:
        YAML-serializable dict, or None if operator not applicable.
    """
    reg = load_operator_registry()
    op_spec = reg.get(operator_name)
    if op_spec is None:
        return None

    # 检查适用性
    if not op_spec["applicable"](model):
        return None

    # 获取固定参数
    const_axes = op_spec["const_axes_fn"](model)
    # 过滤掉 None 值
    const_axes = {k: v for k, v in const_axes.items() if v is not None}

    # 获取变化参数模板
    var_key = op_spec["var_axes_key"]
    var_templates = profile.var_axes.get(var_key, [])
    if not var_templates:
        return None

    # 构建 workloads
    workloads = []
    for tmpl in var_templates:
        if isinstance(tmpl, dict):
            var_axes = dict(tmpl)
        else:
            # 标量值，表示单个变化维度 (如 num_tokens: [32, 64, ...])
            var_axes = {var_key: tmpl}

        stage = _infer_stage(var_axes)
        wl_name = _make_workload_name(model, stage, var_axes)
        source = _make_source_desc(model, stage, var_axes)

        workloads.append({
            "name": wl_name,
            "source": source,
            "var_axes": var_axes,
        })

    case = {
        "definition_name": f"{operator_name}_{model.name}",
        "operator": operator_name,
        "library": op_spec["library"],
        "const_axes": const_axes,
        "workloads": workloads,
    }

    return case


def write_case_yaml(case: dict, output_path: Path) -> None:
    """将 case dict 写入 YAML 文件"""
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # 自定义 yaml dump，保持可读性
    class FlowStyleDumper(yaml.SafeDumper):
        pass

    # 让 var_axes 的值用 flow style（单行显示）
    def represent_var_axes(dumper, data):
        if all(isinstance(v, (int, float, bool, str)) for v in data.values()):
            return dumper.represent_mapping(
                "tag:yaml.org,2002:map", data, flow_style=True
            )
        return dumper.represent_mapping("tag:yaml.org,2002:map", data)

    with open(output_path, "w", encoding="utf-8") as f:
        # 写入头部注释
        f.write(f"# Auto-generated case for {case['operator']} on {case['definition_name'].replace(case['operator'] + '_', '')}\n")
        f.write(f"# Generated by casegen\n\n")
        yaml.safe_dump(case, f, default_flow_style=False, allow_unicode=True, sort_keys=False)


def generate_all(
    models: list[ModelParams],
    operators: list[str] | None,
    profile: Profile,
    output_dir: Path,
    dedup: bool = True,
) -> list[Path]:
    """批量生成用例（按模型目录散落）。

    Args:
        models: 模型列表
        operators: 算子名列表，None 表示全部
        profile: 部署场景
        output_dir: 输出根目录
        dedup: 是否跨模型去重（相同 const_axes 的 case 只保留首次出现）

    Returns:
        生成的文件路径列表
    """
    if operators is None:
        registry = load_operator_registry()
        operators = list(registry.keys())

    # 跨模型去重: key = (op_name, frozenset(const_axes.items()))
    seen_axes: dict[tuple, str] = {}  # key -> first model name

    generated = []
    for model in models:
        for op_name in operators:
            case = generate_case_yaml(model, op_name, profile)
            if case is None:
                continue

            # 跨模型 const_axes 去重
            if dedup:
                axes_key = (op_name, tuple(sorted(case["const_axes"].items())))
                if axes_key in seen_axes:
                    # 跳过重复，在首次生成的 case 中标注
                    continue
                seen_axes[axes_key] = model.name

            output_path = output_dir / model.name / f"{op_name}.yaml"
            write_case_yaml(case, output_path)
            generated.append(output_path)

    return generated


def generate_merged(
    models: list[ModelParams],
    operators: list[str] | None,
    profile: Profile,
    output_dir: Path,
) -> list[Path]:
    """按算子聚合生成用例，跨模型去重后合并为单文件。

    输出结构:
        output_dir/
            mhc_pre.yaml      — 包含所有不同 const_axes 的 workload
            flash_mla.yaml
            ...

    每个 workload 带 source 字段标注来源模型。相同 const_axes 的模型合并，
    workload source 列出所有适用模型。

    Args:
        models: 模型列表
        operators: 算子名列表，None 表示全部
        profile: 部署场景
        output_dir: 输出根目录

    Returns:
        生成的文件路径列表
    """
    if operators is None:
        registry = load_operator_registry()
        operators = list(registry.keys())

    generated = []

    for op_name in operators:
        # 收集所有模型对该算子的 case，按 const_axes 分组
        # key: tuple(sorted(const_axes.items())) -> {const_axes, workloads, models}
        groups: dict[tuple, dict[str, Any]] = {}

        for model in models:
            case = generate_case_yaml(model, op_name, profile)
            if case is None:
                continue

            axes_key = tuple(sorted(case["const_axes"].items()))

            if axes_key not in groups:
                groups[axes_key] = {
                    "const_axes": case["const_axes"],
                    "library": case["library"],
                    "models": [],
                    "workloads": case["workloads"],  # 保留第一个模型的 workloads
                }

            group = groups[axes_key]
            group["models"].append(model.name)

        if not groups:
            continue

        # 构建合并后的 case 文件，每个不同 const_axes 组合一个 section
        sections = []
        for axes_key, group in groups.items():
            # 更新 workload source 字段，标注所有适用模型
            models_tag = " | ".join(group["models"])
            for wl in group["workloads"]:
                wl["source"] = f"[{models_tag}] {wl['source']}"

            section = {
                "const_axes": group["const_axes"],
                "models": group["models"],
                "workloads": group["workloads"],
            }
            sections.append(section)

        merged_case = {
            "operator": op_name,
            "library": next(iter(groups.values()))["library"],
            "sections": sections,
        }

        output_path = output_dir / f"{op_name}.yaml"
        _write_merged_case_yaml(merged_case, output_path)
        generated.append(output_path)

    return generated


def _write_merged_case_yaml(case: dict, output_path: Path) -> None:
    """写入合并后的 case YAML 文件"""
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(f"# Auto-generated merged case for {case['operator']}\n")
        f.write(f"# Generated by casegen (cross-model dedup + merge)\n\n")
        yaml.safe_dump(case, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
